version: '3.7'
services:
    text-generation:
        build: 
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./textgeneration:/usr/src/app/
        ports:
            - 127.0.0.1:8000:8000